services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3070:3070"
      - "3071:3071"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
    command: "node serverReview.js"
    networks:
      - shared-network-6

  mongodb:
    image: mongo:latest
    container_name: mongodbg
    ports:
      - "27022:27017"
    # 💡 فلگ --replSet rs0 اضافه شد و bind_ip اصلاح شد
    command: mongod --bind_ip_all --replSet rs0
    volumes:
      - mongo_data_review:/data/db
    networks:
      - shared-network-6

volumes:
  mongo_data_review:    # نام ولوم یکپارچه شد
    external: true      # به این معنی که قبلاً با دستور docker volume create ساخته شده است

networks:
  shared-network-6:
    driver: bridge
